import { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";

// import Router from "next/router";
// import Input from "../components/Input";
// import DropDown from "../components/DropDown";
// import { Form, Formik } from "formik";
// import { UseAuth } from "../hooks/useAuth";
// import { signOut, useSession } from "next-auth/react";
// import { trpc } from "../utils/trpc";
// import { ROLE } from "@prisma/client";
import Image from "next/image";

import Company from './../../images/asPerson.svg';
import Person from './../../images/asPerson.svg';
import NavBar from '../../components/NavBar'
import Profile from "../../components/Profile";

const SignUp: NextPage = () => {


  return (
    <>
      <Head>
        <title>Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col items-center justify-center space-y-6 container-md mx-24 pb-24">
        <NavBar />
        <div className="flex  w-full gap-4 px-64 justify-between pt-20">
          <Link href={"/auth/person/signup"} className="pointer">
            <div className=" flex flex-col items-center shadow shadow-primaryC px-10 py-8 rounded-3xl ">
              <Image src={Person} alt={"pick person"} width={300} height={300} />
              <h2 className="text-primaryC text-3xl">Person</h2>
            </div>
          </Link>
          <Link href={"/auth/company/signup"} >
            <div className=" flex flex-col items-center shadow shadow-primaryC p-8 rounded-3xl pointer ">
              <Image src={Company} alt={"pick person"} width={300} height={300} />
              <h2 className="text-primaryC text-3xl">Copmany</h2>
            </div>
          </Link>

        </div>
        <div className="">
          <Profile />
        </div>
      </div>
    </>
  );
};

export default SignUp;
