import type { NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { trpc } from "../utils/trpc";
import { UseAuth } from "../hooks/useAuth";
import Input from "../components/Input";

const Home: NextPage = () => {
  const hello = trpc.example.hello.useQuery({ text: "from tRPC" });
  // const { session } = UseAuth();

  return (
    <>
      <Head>
        <title>Hackathon</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center gap-4 p-4">
        <button className="btn btn-primary" onClick={() => signIn()}>
          SignIn
        </button>
        <button className="btn btn-secondary" onClick={() => signOut()}>
          SignOut
        </button>
      </main>
    </>
  );
};

export default Home;
